### ISSUE TITLE
Run v2: newly added link not set to run by default

### ISSUE THREAD

**Issue by jbonisteel** [ooni/run#181]
Steps to reproduce:

- I added a new run link
- Hit run button from dashboard
- scroll down to where the run links are
- the newly added link was not set to run by default - I would think we want it selected by default. Any reason not to? 

![0](https://github.com/ooni/run/assets/15895520/d7bcc899-c71c-4817-ad89-2614948d52b7)

**Comment by aanorbel** [comment]
@jbonisteel ,This is not a glitch. I meant for the app to function in this way. The previous run is tracked and saved as the default on the Run test screen. We can not enable the recently added link by default because it was not there when the tests were last run. That would be altering an app's default behavior without the user's permission.

**Comment by jbonisteel** [comment]
@aanorbel ah okay, understood. I will close this then.
